import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto("http://localhost:4173/", { waitUntil: "networkidle" });
await page.waitForTimeout(400);
const skip = await page.evaluate(() => ({ active: document.activeElement.tagName, skipTransform: document.querySelector('a[href="#main"]').style.transform }));
await page.evaluate(() => window.scrollTo({ top: 2000, behavior: "instant" }));
await page.waitForTimeout(300);
const skipAfter = await page.evaluate(() => ({ active: document.activeElement.tagName, skipTransform: document.querySelector('a[href="#main"]').style.transform }));
const text = await page.evaluate(() => document.querySelector("main").innerText);
const words = ["Imaginez", "Dans un monde", "Que vous soyez", "Découvrez", "innovant", "révolutionnaire", "puissant", "intelligent", "sur mesure", "clé en main", "fluide", "seamless", "Commencer", "En savoir plus", "Découvrir", "—"];
const found = words.map((w) => [w, (text.match(new RegExp(w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi")) || []).length]).filter(([, n]) => n > 0);
const headings = await page.evaluate(() => [...document.querySelectorAll("main h1, main h2, main h3")].map((h) => h.innerText.replace(/\s+/g, " ").trim()));
const questionTitles = headings.filter((h) => h.endsWith("?"));
const ctas = await page.evaluate(() => [...document.querySelectorAll("main a.btn, header a.btn")].map((a) => a.innerText.trim()));
const icons = await page.evaluate(() => document.querySelectorAll("main svg:not(.stage-art):not(.infra-arrow)").length);
const gradients = await page.evaluate(() => [...document.querySelectorAll("main *")].filter((el) => /gradient/.test(getComputedStyle(el).backgroundImage)).map((el) => el.className.toString().split(" ")[0] || el.tagName).slice(0, 10));
const blur = await page.evaluate(() => [...document.querySelectorAll("header, main *")].filter((el) => getComputedStyle(el).backdropFilter !== "none").length);
const aiAsSubject = (text.match(/\bl'IA\b|\bl'intelligence artificielle\b|\bagent IA\b/gi) || []).length;
console.log(JSON.stringify({ skip, skipAfter, found, questionTitles, ctas, inlineIconsOutsideDiagrams: icons, gradientBackgrounds: gradients, backdropBlurElements: blur, mentionsOfIA: aiAsSubject, headings }, null, 1));
await browser.close();
