/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MentiaRouteImport } from './routes/mentia'
import { Route as FiduciaireRouteImport } from './routes/fiduciaire'
import { Route as AthlitRouteImport } from './routes/athlit'
import { Route as IndexRouteImport } from './routes/index'

const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MentiaRoute = MentiaRouteImport.update({
  id: '/mentia',
  path: '/mentia',
  getParentRoute: () => rootRouteImport,
} as any)
const FiduciaireRoute = FiduciaireRouteImport.update({
  id: '/fiduciaire',
  path: '/fiduciaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AthlitRoute = AthlitRouteImport.update({
  id: '/athlit',
  path: '/athlit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlit': typeof AthlitRoute
  '/fiduciaire': typeof FiduciaireRoute
  '/mentia': typeof MentiaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlit': typeof AthlitRoute
  '/fiduciaire': typeof FiduciaireRoute
  '/mentia': typeof MentiaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlit': typeof AthlitRoute
  '/fiduciaire': typeof FiduciaireRoute
  '/mentia': typeof MentiaRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athlit'
    | '/fiduciaire'
    | '/mentia'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athlit'
    | '/fiduciaire'
    | '/mentia'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
  id:
    | '__root__'
    | '/'
    | '/athlit'
    | '/fiduciaire'
    | '/mentia'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthlitRoute: typeof AthlitRoute
  FiduciaireRoute: typeof FiduciaireRoute
  MentiaRoute: typeof MentiaRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentia': {
      id: '/mentia'
      path: '/mentia'
      fullPath: '/mentia'
      preLoaderRoute: typeof MentiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiduciaire': {
      id: '/fiduciaire'
      path: '/fiduciaire'
      fullPath: '/fiduciaire'
      preLoaderRoute: typeof FiduciaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlit': {
      id: '/athlit'
      path: '/athlit'
      fullPath: '/athlit'
      preLoaderRoute: typeof AthlitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthlitRoute: AthlitRoute,
  FiduciaireRoute: FiduciaireRoute,
  MentiaRoute: MentiaRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
